//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TheClubBDModel", "FK_Races_RaceTypes", "RaceType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheClubBDModel.RaceType), "Race", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheClubBDModel.Race), true)]

#endregion

namespace TheClubBDModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TheClubBDEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TheClubBDEntities object using the connection string found in the 'TheClubBDEntities' section of the application configuration file.
        /// </summary>
        public TheClubBDEntities() : base("name=TheClubBDEntities", "TheClubBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TheClubBDEntities object.
        /// </summary>
        public TheClubBDEntities(string connectionString) : base(connectionString, "TheClubBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TheClubBDEntities object.
        /// </summary>
        public TheClubBDEntities(EntityConnection connection) : base(connection, "TheClubBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sponsors> Sponsors
        {
            get
            {
                if ((_Sponsors == null))
                {
                    _Sponsors = base.CreateObjectSet<Sponsors>("Sponsors");
                }
                return _Sponsors;
            }
        }
        private ObjectSet<Sponsors> _Sponsors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Race> Races
        {
            get
            {
                if ((_Races == null))
                {
                    _Races = base.CreateObjectSet<Race>("Races");
                }
                return _Races;
            }
        }
        private ObjectSet<Race> _Races;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RaceType> RaceTypes
        {
            get
            {
                if ((_RaceTypes == null))
                {
                    _RaceTypes = base.CreateObjectSet<RaceType>("RaceTypes");
                }
                return _RaceTypes;
            }
        }
        private ObjectSet<RaceType> _RaceTypes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sponsors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSponsors(Sponsors sponsors)
        {
            base.AddObject("Sponsors", sponsors);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Races EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRaces(Race race)
        {
            base.AddObject("Races", race);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RaceTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRaceTypes(RaceType raceType)
        {
            base.AddObject("RaceTypes", raceType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TheClubBDModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="memberID">Initial value of the MemberID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="secondName">Initial value of the SecondName property.</param>
        /// <param name="eMail">Initial value of the eMail property.</param>
        /// <param name="bDate">Initial value of the BDate property.</param>
        /// <param name="regDate">Initial value of the RegDate property.</param>
        /// <param name="federated">Initial value of the Federated property.</param>
        public static Member CreateMember(global::System.Int32 memberID, global::System.String name, global::System.String secondName, global::System.String eMail, global::System.DateTime bDate, global::System.DateTime regDate, global::System.Boolean federated)
        {
            Member member = new Member();
            member.MemberID = memberID;
            member.Name = name;
            member.SecondName = secondName;
            member.eMail = eMail;
            member.BDate = bDate;
            member.RegDate = regDate;
            member.Federated = federated;
            return member;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value, "MemberID");
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecondName
        {
            get
            {
                return _SecondName;
            }
            set
            {
                OnSecondNameChanging(value);
                ReportPropertyChanging("SecondName");
                _SecondName = StructuralObject.SetValidValue(value, false, "SecondName");
                ReportPropertyChanged("SecondName");
                OnSecondNameChanged();
            }
        }
        private global::System.String _SecondName;
        partial void OnSecondNameChanging(global::System.String value);
        partial void OnSecondNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eMail
        {
            get
            {
                return _eMail;
            }
            set
            {
                OneMailChanging(value);
                ReportPropertyChanging("eMail");
                _eMail = StructuralObject.SetValidValue(value, false, "eMail");
                ReportPropertyChanged("eMail");
                OneMailChanged();
            }
        }
        private global::System.String _eMail;
        partial void OneMailChanging(global::System.String value);
        partial void OneMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BDate
        {
            get
            {
                return _BDate;
            }
            set
            {
                OnBDateChanging(value);
                ReportPropertyChanging("BDate");
                _BDate = StructuralObject.SetValidValue(value, "BDate");
                ReportPropertyChanged("BDate");
                OnBDateChanged();
            }
        }
        private global::System.DateTime _BDate;
        partial void OnBDateChanging(global::System.DateTime value);
        partial void OnBDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegDate
        {
            get
            {
                return _RegDate;
            }
            set
            {
                OnRegDateChanging(value);
                ReportPropertyChanging("RegDate");
                _RegDate = StructuralObject.SetValidValue(value, "RegDate");
                ReportPropertyChanged("RegDate");
                OnRegDateChanged();
            }
        }
        private global::System.DateTime _RegDate;
        partial void OnRegDateChanging(global::System.DateTime value);
        partial void OnRegDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Federated
        {
            get
            {
                return _Federated;
            }
            set
            {
                OnFederatedChanging(value);
                ReportPropertyChanging("Federated");
                _Federated = StructuralObject.SetValidValue(value, "Federated");
                ReportPropertyChanged("Federated");
                OnFederatedChanged();
            }
        }
        private global::System.Boolean _Federated;
        partial void OnFederatedChanging(global::System.Boolean value);
        partial void OnFederatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addres
        {
            get
            {
                return _Addres;
            }
            set
            {
                OnAddresChanging(value);
                ReportPropertyChanging("Addres");
                _Addres = StructuralObject.SetValidValue(value, true, "Addres");
                ReportPropertyChanged("Addres");
                OnAddresChanged();
            }
        }
        private global::System.String _Addres;
        partial void OnAddresChanging(global::System.String value);
        partial void OnAddresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AddresNumber
        {
            get
            {
                return _AddresNumber;
            }
            set
            {
                OnAddresNumberChanging(value);
                ReportPropertyChanging("AddresNumber");
                _AddresNumber = StructuralObject.SetValidValue(value, "AddresNumber");
                ReportPropertyChanged("AddresNumber");
                OnAddresNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _AddresNumber;
        partial void OnAddresNumberChanging(Nullable<global::System.Int32> value);
        partial void OnAddresNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPost
        {
            get
            {
                return _CPost;
            }
            set
            {
                OnCPostChanging(value);
                ReportPropertyChanging("CPost");
                _CPost = StructuralObject.SetValidValue(value, true, "CPost");
                ReportPropertyChanged("CPost");
                OnCPostChanged();
            }
        }
        private global::System.String _CPost;
        partial void OnCPostChanging(global::System.String value);
        partial void OnCPostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Town
        {
            get
            {
                return _Town;
            }
            set
            {
                OnTownChanging(value);
                ReportPropertyChanging("Town");
                _Town = StructuralObject.SetValidValue(value, true, "Town");
                ReportPropertyChanged("Town");
                OnTownChanged();
            }
        }
        private global::System.String _Town;
        partial void OnTownChanging(global::System.String value);
        partial void OnTownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, true, "Province");
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true, "Country");
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tlf
        {
            get
            {
                return _tlf;
            }
            set
            {
                OntlfChanging(value);
                ReportPropertyChanging("tlf");
                _tlf = StructuralObject.SetValidValue(value, true, "tlf");
                ReportPropertyChanged("tlf");
                OntlfChanged();
            }
        }
        private global::System.String _tlf;
        partial void OntlfChanging(global::System.String value);
        partial void OntlfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tlfMobile
        {
            get
            {
                return _tlfMobile;
            }
            set
            {
                OntlfMobileChanging(value);
                ReportPropertyChanging("tlfMobile");
                _tlfMobile = StructuralObject.SetValidValue(value, true, "tlfMobile");
                ReportPropertyChanged("tlfMobile");
                OntlfMobileChanged();
            }
        }
        private global::System.String _tlfMobile;
        partial void OntlfMobileChanging(global::System.String value);
        partial void OntlfMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value, true, "DNI");
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private global::System.String _DNI;
        partial void OnDNIChanging(global::System.String value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> theClubNumer
        {
            get
            {
                return _theClubNumer;
            }
            set
            {
                OntheClubNumerChanging(value);
                ReportPropertyChanging("theClubNumer");
                _theClubNumer = StructuralObject.SetValidValue(value, "theClubNumer");
                ReportPropertyChanged("theClubNumer");
                OntheClubNumerChanged();
            }
        }
        private Nullable<global::System.Int32> _theClubNumer;
        partial void OntheClubNumerChanging(Nullable<global::System.Int32> value);
        partial void OntheClubNumerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photoUrl
        {
            get
            {
                return _photoUrl;
            }
            set
            {
                OnphotoUrlChanging(value);
                ReportPropertyChanging("photoUrl");
                _photoUrl = StructuralObject.SetValidValue(value, true, "photoUrl");
                ReportPropertyChanged("photoUrl");
                OnphotoUrlChanged();
            }
        }
        private global::System.String _photoUrl;
        partial void OnphotoUrlChanging(global::System.String value);
        partial void OnphotoUrlChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TheClubBDModel", Name="Race")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Race : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="raceTypeId">Initial value of the RaceTypeId property.</param>
        public static Race CreateRace(global::System.Int32 id, global::System.String name, global::System.DateTime date, global::System.Int32 raceTypeId)
        {
            Race race = new Race();
            race.Id = id;
            race.Name = name;
            race.Date = date;
            race.RaceTypeId = raceTypeId;
            return race;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, true, "Ciudad");
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provincia
        {
            get
            {
                return _Provincia;
            }
            set
            {
                OnProvinciaChanging(value);
                ReportPropertyChanging("Provincia");
                _Provincia = StructuralObject.SetValidValue(value, true, "Provincia");
                ReportPropertyChanged("Provincia");
                OnProvinciaChanged();
            }
        }
        private global::System.String _Provincia;
        partial void OnProvinciaChanging(global::System.String value);
        partial void OnProvinciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pais
        {
            get
            {
                return _Pais;
            }
            set
            {
                OnPaisChanging(value);
                ReportPropertyChanging("Pais");
                _Pais = StructuralObject.SetValidValue(value, true, "Pais");
                ReportPropertyChanged("Pais");
                OnPaisChanged();
            }
        }
        private global::System.String _Pais;
        partial void OnPaisChanging(global::System.String value);
        partial void OnPaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RaceTypeId
        {
            get
            {
                return _RaceTypeId;
            }
            set
            {
                OnRaceTypeIdChanging(value);
                ReportPropertyChanging("RaceTypeId");
                _RaceTypeId = StructuralObject.SetValidValue(value, "RaceTypeId");
                ReportPropertyChanged("RaceTypeId");
                OnRaceTypeIdChanged();
            }
        }
        private global::System.Int32 _RaceTypeId;
        partial void OnRaceTypeIdChanging(global::System.Int32 value);
        partial void OnRaceTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                OnMemoChanging(value);
                ReportPropertyChanging("Memo");
                _Memo = StructuralObject.SetValidValue(value, true, "Memo");
                ReportPropertyChanged("Memo");
                OnMemoChanged();
            }
        }
        private global::System.String _Memo;
        partial void OnMemoChanging(global::System.String value);
        partial void OnMemoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TheClubBDModel", "FK_Races_RaceTypes", "RaceType")]
        public RaceType RaceType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RaceType>("TheClubBDModel.FK_Races_RaceTypes", "RaceType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RaceType>("TheClubBDModel.FK_Races_RaceTypes", "RaceType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RaceType> RaceTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RaceType>("TheClubBDModel.FK_Races_RaceTypes", "RaceType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RaceType>("TheClubBDModel.FK_Races_RaceTypes", "RaceType", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TheClubBDModel", Name="RaceType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RaceType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RaceType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="puntosPart">Initial value of the PuntosPart property.</param>
        public static RaceType CreateRaceType(global::System.Int32 id, global::System.String name, global::System.Int32 puntosPart)
        {
            RaceType raceType = new RaceType();
            raceType.Id = id;
            raceType.Name = name;
            raceType.PuntosPart = puntosPart;
            return raceType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PuntosPart
        {
            get
            {
                return _PuntosPart;
            }
            set
            {
                OnPuntosPartChanging(value);
                ReportPropertyChanging("PuntosPart");
                _PuntosPart = StructuralObject.SetValidValue(value, "PuntosPart");
                ReportPropertyChanged("PuntosPart");
                OnPuntosPartChanged();
            }
        }
        private global::System.Int32 _PuntosPart;
        partial void OnPuntosPartChanging(global::System.Int32 value);
        partial void OnPuntosPartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                OnMemoChanging(value);
                ReportPropertyChanging("Memo");
                _Memo = StructuralObject.SetValidValue(value, true, "Memo");
                ReportPropertyChanged("Memo");
                OnMemoChanged();
            }
        }
        private global::System.String _Memo;
        partial void OnMemoChanging(global::System.String value);
        partial void OnMemoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TheClubBDModel", "FK_Races_RaceTypes", "Race")]
        public EntityCollection<Race> Races
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Race>("TheClubBDModel.FK_Races_RaceTypes", "Race");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Race>("TheClubBDModel.FK_Races_RaceTypes", "Race", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TheClubBDModel", Name="Sponsors")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sponsors : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sponsors object.
        /// </summary>
        /// <param name="sponsorID">Initial value of the SponsorID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="personaContacto">Initial value of the PersonaContacto property.</param>
        /// <param name="fechaAlta">Initial value of the FechaAlta property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static Sponsors CreateSponsors(global::System.Int32 sponsorID, global::System.String nombre, global::System.String personaContacto, global::System.DateTime fechaAlta, global::System.Boolean activo)
        {
            Sponsors sponsors = new Sponsors();
            sponsors.SponsorID = sponsorID;
            sponsors.Nombre = nombre;
            sponsors.PersonaContacto = personaContacto;
            sponsors.FechaAlta = fechaAlta;
            sponsors.Activo = activo;
            return sponsors;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SponsorID
        {
            get
            {
                return _SponsorID;
            }
            set
            {
                if (_SponsorID != value)
                {
                    OnSponsorIDChanging(value);
                    ReportPropertyChanging("SponsorID");
                    _SponsorID = StructuralObject.SetValidValue(value, "SponsorID");
                    ReportPropertyChanged("SponsorID");
                    OnSponsorIDChanged();
                }
            }
        }
        private global::System.Int32 _SponsorID;
        partial void OnSponsorIDChanging(global::System.Int32 value);
        partial void OnSponsorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PersonaContacto
        {
            get
            {
                return _PersonaContacto;
            }
            set
            {
                OnPersonaContactoChanging(value);
                ReportPropertyChanging("PersonaContacto");
                _PersonaContacto = StructuralObject.SetValidValue(value, false, "PersonaContacto");
                ReportPropertyChanged("PersonaContacto");
                OnPersonaContactoChanged();
            }
        }
        private global::System.String _PersonaContacto;
        partial void OnPersonaContactoChanging(global::System.String value);
        partial void OnPersonaContactoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return _FechaAlta;
            }
            set
            {
                OnFechaAltaChanging(value);
                ReportPropertyChanging("FechaAlta");
                _FechaAlta = StructuralObject.SetValidValue(value, "FechaAlta");
                ReportPropertyChanged("FechaAlta");
                OnFechaAltaChanged();
            }
        }
        private global::System.DateTime _FechaAlta;
        partial void OnFechaAltaChanging(global::System.DateTime value);
        partial void OnFechaAltaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value, "Activo");
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                OnMemoChanging(value);
                ReportPropertyChanging("Memo");
                _Memo = StructuralObject.SetValidValue(value, true, "Memo");
                ReportPropertyChanged("Memo");
                OnMemoChanged();
            }
        }
        private global::System.String _Memo;
        partial void OnMemoChanging(global::System.String value);
        partial void OnMemoChanged();

        #endregion

    }

    #endregion

}
